[tool.black]
line-length = 88
target-version = ['py313']

[tool.isort]
profile = "black"  # КРИТИЧЕСКИ ВАЖНО!
line_length = 88
multi_line_output = 3  # Совместимость с black
include_trailing_comma = true
force_sort_within_sections = true
